//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EczaDepoUygulama.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class ilactbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ilactbl()
        {
            this.satislartbl = new HashSet<satislartbl>();
            this.MarkaListesi = new List<SelectListItem>();
            MarkaListesi.Insert(0, new SelectListItem { Text = "Önce kategori seçilmeli", Value = "" });
        }
    
        public int ilac_id { get; set; }
        public string ilac_adi { get; set; }
        public int kategori_id { get; set; }
        public int marka_id { get; set; }
        public string barkod_no { get; set; }
        public decimal? alis_fiyati { get; set; }
        public decimal? satis_fiyati { get; set; }
        public int? kdv { get; set; }
        public int birim_id { get; set; }
        public System.DateTime tarih { get; set; }
        public Nullable<decimal> miktari { get; set; }
    
        public virtual birimtbl birimtbl { get; set; }
        public virtual kategorilertbl kategorilertbl { get; set; }
        public virtual markalartbl markalartbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satislartbl> satislartbl { get; set; }

        public List<SelectListItem> KategoriListesi { get; set; }
        public List<SelectListItem> MarkaListesi { get; set; }
        public List<SelectListItem> BirimListesi { get; set; } 
    }
}
