//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EczaDepoUygulama.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class musterilertbl
    {
        public int musteri_id { get; set; }
        public string musteri_ad { get; set; }
        public string musteri_tel { get; set; }
        public string musteri_adres { get; set; }
        public string musteri_mail { get; set; }
        public string musteri_foto { get; set; }
        public System.DateTime musteri_kayit_tarih { get; set; }
        public decimal musteri_puan { get; set; }
        public string aciklama { get; set; }
    }
}
