//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EczaDepoUygulama.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class satislartbl
    {
        public int satis_id { get; set; }
        public int ilac_id { get; set; }
        public int sepet_id { get; set; }
        public string barkod_no { get; set; }
        public decimal birim_fiyati { get; set; }
        public decimal toplam_fiyati { get; set; }
        public int kdv { get; set; }
        public int birim_id { get; set; }
        public System.DateTime tarih { get; set; }
        public System.DateTime saat { get; set; }
        public decimal miktari { get; set; }
    
        public virtual ilactbl ilactbl { get; set; }
    }
}
